name: TheAPI
main: me.devtec.theapi.bukkit.BukkitLoader
version: 12.9.2
author: DevTec, Straikerinos
website: https://www.spigotmc.org/resources/72679/
api-version: 1.13
softdepend: [Vault,PlaceholderAPI,HeadDatabase]
spigot-id: 72679
load: STARTUP